# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mshare < Formula
  desc "Command-line tool for the Microshare IoT platform"
  homepage "https://github.com/microshare/mshare-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/microshare/mshare-cli/releases/download/v1.0.3/mshare_1.0.3_darwin_amd64.tar.gz"
      sha256 "dd12307a264830ecab4efd17e85baa0837832ef758a1f0c7dced0e5c8a50f743"

      define_method(:install) do
        bin.install "mshare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/microshare/mshare-cli/releases/download/v1.0.3/mshare_1.0.3_darwin_arm64.tar.gz"
      sha256 "30f84504c8b276f924a06bd43ff03f5f0135b6681445b08f253fe39c0d137d1a"

      define_method(:install) do
        bin.install "mshare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/microshare/mshare-cli/releases/download/v1.0.3/mshare_1.0.3_linux_amd64.tar.gz"
      sha256 "58ceb0f55985d45048b3fee4fb29697ed88d0ec88822eb92ea410583927dd6bc"
      define_method(:install) do
        bin.install "mshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/microshare/mshare-cli/releases/download/v1.0.3/mshare_1.0.3_linux_arm64.tar.gz"
      sha256 "260ceebeca790d01a298badd284aeda85964dd233b1bf1b29d69be4d0fb3ed32"
      define_method(:install) do
        bin.install "mshare"
      end
    end
  end

  test do
    system "#{bin}/mshare", "--version"
  end
end
