# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mshare < Formula
  desc "Command-line tool for the Microshare IoT platform"
  homepage "https://github.com/microshare/mshare-cli"
  version "1.0.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/microshare/homebrew-tap/releases/download/v1.0.14/mshare_1.0.14_darwin_amd64.tar.gz"
      sha256 "c7bb862decf3ef0f416889cfc8b0737b1f17d7faa227fda58c63d7d545110be3"

      define_method(:install) do
        bin.install "mshare"
        bin.install "mshare-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/microshare/homebrew-tap/releases/download/v1.0.14/mshare_1.0.14_darwin_arm64.tar.gz"
      sha256 "c5272e33bf74d75ab5bb013d8886920e03d70ade43530ab1ac8b6b3e33ec0a55"

      define_method(:install) do
        bin.install "mshare"
        bin.install "mshare-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/microshare/homebrew-tap/releases/download/v1.0.14/mshare_1.0.14_linux_amd64.tar.gz"
      sha256 "ac9d83564caf5fb951defe6934377642ce582f961d194fa0e7377f3553ca34e9"
      define_method(:install) do
        bin.install "mshare"
        bin.install "mshare-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/microshare/homebrew-tap/releases/download/v1.0.14/mshare_1.0.14_linux_arm64.tar.gz"
      sha256 "c42cc2fc20fc963fd9ec5bbcab7962b19cfbf4cbda8bf3bea754c1480a9e7e6e"
      define_method(:install) do
        bin.install "mshare"
        bin.install "mshare-mcp"
      end
    end
  end

  test do
    system "#{bin}/mshare", "--version"
    system "#{bin}/mshare-mcp", "--version"
  end
end
